tunnel: EOYWebTunnel
credentials-file: C:\Users\julia\.cloudflared\20810fd8-7bec-4d7e-800e-27ab00d6252f.json

ingress:
  - hostname: api.frisco-cs.com
    service: http://127.0.0.1:3000
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      http2Origin: false
      disableChunkedEncoding: true
      httpHostHeader: api.frisco-cs
  - service: http_status:404